// Package testenv provides functions and data structures for
// constructing and manipulating a temporary environment for
// use during automated testing.
//
// The testenv package should only be used in tests.
package testenv

import (
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"testing"
	"time"

	"github.com/spf13/viper"
	"github.com/stretchr/testify/assert"
)

type TestEnv struct {
	t       *testing.T
	b       *testing.B
	BaseDir string
}

// New creates a test environment in a temporary directory and configures
// Viper to use it.
//
// Caller is responsible to delete env.BaseDir by calling
// env.RemoveAll.
//
// Asserts no errors occur.
func New(t *testing.T) (env *TestEnv) {
	env = new(TestEnv)
	env.t = t
	env.init()
	return env
}

// NewBenchmark creates a benchmark environment in a temporary directory and configures
// Viper to use it.
//
// Caller is responsible to delete env.BaseDir by calling
// env.RemoveAll.
//
// Asserts no errors occur.
func NewBenchmark(b *testing.B) (env *TestEnv) {
	env = new(TestEnv)
	env.b = b
	env.init()
	return env
}

// init creates a temporary directory and configured Viper to use it.
//
// Asserts no errors occur.
func (env *TestEnv) init() {
	tmpDir, err := os.MkdirTemp(os.TempDir(), "allmend-test-*")
	env.assertNoError(err)
	env.BaseDir = tmpDir

	// Setup config file
	configDir := filepath.Join(env.BaseDir, "config")
	err = os.MkdirAll(configDir, 0755)
	env.assertNoError(err)

	agentsDir := filepath.Join(env.BaseDir, "agents")
	err = os.MkdirAll(agentsDir, 0755)
	env.assertNoError(err)

	// Create config content with absolute path to agents dir
	configContent := "agent_paths:\n  - " + agentsDir + "\n"

	configFile := filepath.Join(configDir, "allmend.conf")
	err = os.WriteFile(configFile, []byte(configContent), 0644)
	env.assertNoError(err)

	// Configure Viper to use this config file
	viper.SetConfigFile(configFile)
	viper.SetConfigType("yaml")
	err = viper.ReadInConfig()
	env.assertNoError(err)
}

// assertNoError handles error conditions generated by env,
// using the semantics of either a testing or a benchmark environment.
func (env *TestEnv) assertNoError(err error, msgAndArgs ...interface{}) {
	if env.t != nil {
		assert.NoError(env.t, err, msgAndArgs...)
	}

	if env.b != nil && err != nil {
		if len(msgAndArgs) == 0 {
			env.b.Errorf("%s", err)
		} else {
			env.b.Errorf(msgAndArgs[0].(string), (msgAndArgs[1:])...)
		}
	}
}

// GetPath returns the absolute path name for fileName specified
// relative to the test environment.
func (env *TestEnv) GetPath(fileName string) string {
	return path.Join(env.BaseDir, fileName)
}

// MkdirAll creates dirName and any intermediate directories relative
// to the test environment.
//
// Asserts no errors occur.
func (env *TestEnv) MkdirAll(dirName string) {
	err := os.MkdirAll(env.GetPath(dirName), 0755)
	env.assertNoError(err)
}

// Chmod changes the mode of fileName in the test environment, which must already exist.
//
// Asserts no errors occur.
func (env *TestEnv) Chmod(fileName string, mode int) {
	err := os.Chmod(env.GetPath(fileName), os.FileMode(mode))
	env.assertNoError(err)
}

// WriteFile writes content to fileName, creating any necessary
// intermediate directories relative to the test environment.
//
// Asserts no errors occur.
func (env *TestEnv) WriteFile(fileName string, content string) {
	dirName := filepath.Dir(fileName)
	env.MkdirAll(dirName)

	f, err := os.Create(env.GetPath(fileName))
	env.assertNoError(err)
	defer f.Close()
	_, err = f.WriteString(content)
	env.assertNoError(err)
	// Set fixed time for reproducibility if needed, or just ignore
	err = os.Chtimes(env.GetPath(fileName),
		time.Date(2026, time.February, 1, 3, 4, 5, 0, time.UTC),
		time.Date(2026, time.February, 1, 3, 4, 5, 0, time.UTC))
	env.assertNoError(err)
}

// ImportFile writes the contents of inputFileName to fileName,
// creating any necessary intermediate directories relative to the
// test environment.
func (env *TestEnv) ImportFile(fileName string, inputFileName string) {
	buffer, err := os.ReadFile(inputFileName)
	env.assertNoError(err)
	env.WriteFile(fileName, string(buffer))
}

func (env *TestEnv) ImportDir(dirName string, inputDirName string) {
	env.MkdirAll(path.Dir(dirName))
	cmd := exec.Command("cp", "--recursive", inputDirName, env.GetPath(dirName))
	output, err := cmd.CombinedOutput()
	env.assertNoError(err, string(output))
}

// CreateFile creates an empty file at fileName, creating any necessary intermediate directories
// relative to the test environment.
func (env *TestEnv) CreateFile(fileName string) {
	env.WriteFile(fileName, "")
}

// Symlink creates a symlink at fileName to target, creating any necessary intermediate directories
// relative to the test environment.
func (env *TestEnv) Symlink(target string, fileName string) {
	dirName := filepath.Dir(fileName)
	env.MkdirAll(dirName)

	err := os.Symlink(target, env.GetPath(fileName))
	env.assertNoError(err)
}

// ReadFile returns the content of fileName as converted to a
// string.
//
// Asserts no errors occur.
func (env *TestEnv) ReadFile(fileName string) string {
	buffer, err := os.ReadFile(env.GetPath(fileName))
	env.assertNoError(err)
	return string(buffer)
}

// ReadDir returns the content of dirName as converted to a
// slice of strings.
//
// Asserts no errors occur.
func (env *TestEnv) ReadDir(dirName string) []string {
	entries, err := os.ReadDir(env.GetPath(dirName))
	env.assertNoError(err)
	var entryStrs []string
	for _, entry := range entries {
		entryStrs = append(entryStrs, entry.Name())
	}
	return entryStrs
}

// RemoveAll deletes the temporary directory, and all its contents,
// for the test environment.
//
// Asserts no errors occur.
func (env *TestEnv) RemoveAll() {
	err := os.RemoveAll(env.BaseDir)
	env.assertNoError(err)
}
